import {
  BUILTIN_VACE_DEFAULT_ID,
  BUILTIN_VACE_PRESET,
  DEFAULT_VACE_PHASE_CONFIG,
  VACE_FEATURED_PRESET_IDS,
} from '@/shared/lib/vaceDefaults';

export const DEFAULT_JOIN_CLIPS_PHASE_CONFIG = DEFAULT_VACE_PHASE_CONFIG;
export const BUILTIN_JOIN_CLIPS_DEFAULT_ID = BUILTIN_VACE_DEFAULT_ID;
export const BUILTIN_JOIN_CLIPS_PRESET = BUILTIN_VACE_PRESET;
export const JOIN_CLIPS_FEATURED_PRESET_IDS = VACE_FEATURED_PRESET_IDS;
